### ISSUE TITLE
[Feature]: Implement Read/Write traits for embedded_io::{Read,Write}

### ISSUE THREAD

**Issue by elrafoon** [enarx/ciborium#105] opened 2024-02-16 15:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dear maintainers,

I think it would be very useful to have support for embedded_io traits right in the ciborium - implement ciborium::{Read,Write} for embedded_io::{Read,Write}.

I have already implemented it, but now I realized one problem - ciborium currently sets MSRV to 1.58.

With rust 1.58, there is no support for optional dependencies (so I can't make embedded-io optional) and also limits embedded-io version to 0.5.0 (while current is 0.6.1).

See [pull request](https://github.com/enarx/ciborium/pull/104)

How shall I proceed?

**Comment by rjzak** [comment] 2024-02-16 15:56
I have a PR open to boost the MSRV https://github.com/enarx/ciborium/pull/103, and it's stuck on an unrelated unit test that fails. I can force it, but I'd appreciate help on trying to figure out the cause.

**Comment by rjzak** [comment] 2024-02-17 00:20
Closed via https://github.com/enarx/ciborium/pull/104

**Closed by rjzak** 2024-02-17 00:20 UTC
Labels: enhancement
